
services:
  - type: web
    name: lens5-laravel
    env: docker
    plan: free
    branch: main
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:NWQf3OsJPfGp2KSgfdeeElwKSRPPsAWQcBufyRjBx6s=
      - key: APP_URL
        value: https://lens5.onrender.com
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-mysql-host.render.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: lens5_db
      - key: DB_USERNAME
        value: your_db_user
      - key: DB_PASSWORD
        value: your_db_password
      - key: SESSION_DRIVER
        value: database
      - key: LOG_CHANNEL
        value: stack
